<?php
    $fmtMoney = fn($v) => '₱' . number_format((float) ($v ?? 0), 2);
    $byClassification = $by_classification ?? collect();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Assessment Report</title>
    <style>
        @page { margin: 20px 24px; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 9.5px; color: #111; }
        h1.title { text-align: center; font-size: 15px; font-weight: bold; margin: 0 0 2px 0; letter-spacing: 0.5px; }
        p.subtitle { text-align: center; font-size: 9px; color: #555; margin: 0 0 16px 0; }
        .summary { width: 100%; margin-bottom: 16px; }
        .summary td { width: 50%; padding: 10px 14px; border: 1px solid #999; }
        .summary .label { font-size: 8.5px; color: #555; text-transform: uppercase; letter-spacing: 0.03em; }
        .summary .value { font-size: 16px; font-weight: bold; color: #1a3557; margin-top: 4px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th, table.data td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        table.data th { background: #1a3557; color: #fff; font-size: 8.5px; text-transform: uppercase; }
        table.data tr:nth-child(even) td { background: #f5f7fa; }
        .num { text-align: right; white-space: nowrap; }
        .footer { margin-top: 10px; font-size: 8px; color: #777; text-align: right; }
    </style>
</head>
<body>
    <h1 class="title">Assessment Report</h1>
    <p class="subtitle">Approved Properties Only &middot; Generated {{ $generatedAt->format('F d, Y g:i A') }}</p>

    <table class="summary">
        <tr>
            <td>
                <div class="label">Total Market Value</div>
                <div class="value">{{ $fmtMoney($total_market_value) }}</div>
            </td>
            <td>
                <div class="label">Total Assessed Value</div>
                <div class="value">{{ $fmtMoney($total_assessed_value) }}</div>
            </td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th>Classification</th>
                <th class="num">Count</th>
                <th class="num">Total Market Value</th>
                <th class="num">Total Assessed Value</th>
            </tr>
        </thead>
        <tbody>
            @forelse($byClassification as $row)
                <tr>
                    <td>{{ $row->classification?->name ?? '—' }}</td>
                    <td class="num">{{ $row->count }}</td>
                    <td class="num">{{ $fmtMoney($row->total_market) }}</td>
                    <td class="num">{{ $fmtMoney($row->total_assessed) }}</td>
                </tr>
            @empty
                <tr><td colspan="4" style="text-align:center; padding:14px;">No approved records found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <p class="footer">Page generated by TDMS &middot; {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
</body>
</html>
