<?php
    $eventLabel = fn($e) => $e ? ucwords(str_replace('_', ' ', $e)) : '—';
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Report</title>
    <style>
        @page { margin: 20px 24px; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 9px; color: #111; }
        h1.title { text-align: center; font-size: 15px; font-weight: bold; margin: 0 0 2px 0; letter-spacing: 0.5px; }
        p.subtitle { text-align: center; font-size: 9px; color: #555; margin: 0 0 12px 0; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #999; padding: 4px 6px; text-align: left; }
        th { background: #1a3557; color: #fff; font-size: 8.5px; text-transform: uppercase; }
        tr:nth-child(even) td { background: #f5f7fa; }
        .mono { font-family: DejaVu Sans Mono, monospace; font-size: 8px; }
        .meta { font-size: 8.5px; color: #444; margin-bottom: 10px; }
        .footer { margin-top: 10px; font-size: 8px; color: #777; text-align: right; }
    </style>
</head>
<body>
    <h1 class="title">Audit Report</h1>
    <p class="subtitle">System Activity Log &middot; Generated {{ $generatedAt->format('F d, Y g:i A') }}</p>

    <div class="meta"><strong>Total Records:</strong> {{ count($logs) }}</div>

    <table>
        <thead>
            <tr>
                <th style="width:18%">User</th>
                <th style="width:20%">Event</th>
                <th style="width:14%">IP Address</th>
                <th style="width:48%">Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($logs as $log)
                <tr>
                    <td>{{ $log->user?->name ?? 'System' }}</td>
                    <td class="mono">{{ $eventLabel($log->event) }}</td>
                    <td class="mono">{{ $log->ip_address ?? '—' }}</td>
                    <td>{{ $log->created_at?->format('F d, Y g:i:s A') }}</td>
                </tr>
            @empty
                <tr><td colspan="4" style="text-align:center; padding:14px;">No audit log entries found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <p class="footer">Page generated by TDMS &middot; {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
</body>
</html>
