<?php
    $fmtMoney = fn($v) => '₱' . number_format((float) ($v ?? 0), 2);
    $statusLabel = fn($s) => $s ? ucwords(str_replace('_', ' ', $s)) : '—';

    $filterLines = [];
    if (!empty($filters['status'])) $filterLines[] = 'Status: ' . $statusLabel($filters['status']);
    if (!empty($filters['date_from'])) $filterLines[] = 'From: ' . $filters['date_from'];
    if (!empty($filters['date_to'])) $filterLines[] = 'To: ' . $filters['date_to'];
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Property Report</title>
    <style>
        @page { margin: 20px 24px; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 9px; color: #111; }
        h1.title { text-align: center; font-size: 15px; font-weight: bold; margin: 0 0 2px 0; letter-spacing: 0.5px; }
        p.subtitle { text-align: center; font-size: 9px; color: #555; margin: 0 0 12px 0; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #999; padding: 4px 5px; text-align: left; vertical-align: top; }
        th { background: #1a3557; color: #fff; font-size: 8.5px; text-transform: uppercase; }
        tr:nth-child(even) td { background: #f5f7fa; }
        .num { text-align: right; white-space: nowrap; }
        .meta { font-size: 8.5px; color: #444; margin-bottom: 10px; }
        .totals td { font-weight: bold; background: #eef2f7 !important; }
        .footer { margin-top: 10px; font-size: 8px; color: #777; text-align: right; }
    </style>
</head>
<body>
    <h1 class="title">Property Report</h1>
    <p class="subtitle">Municipality Assessor's Office &middot; Generated {{ $generatedAt->format('F d, Y g:i A') }}</p>

    <div class="meta">
        <strong>Total Records:</strong> {{ count($records) }}
        @if(count($filterLines))
            &nbsp;|&nbsp; <strong>Filters:</strong> {{ implode(' · ', $filterLines) }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th style="width:12%">TD Number</th>
                <th style="width:18%">Owner</th>
                <th style="width:14%">Classification</th>
                <th style="width:14%">Barangay</th>
                <th style="width:14%" class="num">Market Value</th>
                <th style="width:14%" class="num">Assessed Value</th>
                <th style="width:14%">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $r)
                <tr>
                    <td>{{ $r->td_number }}</td>
                    <td>{{ $r->owner?->owner_name ?? '—' }}</td>
                    <td>{{ $r->classification?->name ?? '—' }}</td>
                    <td>{{ $r->barangay?->name ?? '—' }}</td>
                    <td class="num">{{ $fmtMoney($r->market_value) }}</td>
                    <td class="num">{{ $fmtMoney($r->assessed_value) }}</td>
                    <td>{{ $statusLabel($r->status) }}</td>
                </tr>
            @empty
                <tr><td colspan="7" style="text-align:center; padding:14px;">No records match the selected filters.</td></tr>
            @endforelse
        </tbody>
        @if(count($records))
            <tfoot>
                <tr class="totals">
                    <td colspan="4" style="text-align:right;">TOTALS</td>
                    <td class="num">{{ $fmtMoney($total_market_value) }}</td>
                    <td class="num">{{ $fmtMoney($total_assessed_value) }}</td>
                    <td></td>
                </tr>
            </tfoot>
        @endif
    </table>

    <p class="footer">Page generated by TDMS &middot; {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
</body>
</html>
